namespace Databox.Libs.Jobboerse
{
	partial class ucExtSettings
	{
		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            this.label1 = new System.Windows.Forms.Label();
            this.CityCbx = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.KeywordTbx = new System.Windows.Forms.TextBox();
            this.bsSett = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.bsSett)).BeginInit();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(105, 49);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(42, 19);
            this.label1.TabIndex = 0;
            this.label1.Text = "City:";
            // 
            // CityCbx
            // 
            this.CityCbx.FormattingEnabled = true;
            this.CityCbx.Items.AddRange(new object[] {
            "Aachen",
            "Aalen",
            "Aalen-Wasseralfingen",
            "Ahaus",
            "Ahrweiler",
            "Aichach",
            "Alfeld",
            "Alsfeld",
            "Altdorf bei Nürnberg",
            "Altena",
            "Altenburg",
            "Altenkirchen",
            "Altentreptow",
            "Altötting",
            "Alzenau in Unterfranken",
            "Alzey",
            "Amberg",
            "Angermünde",
            "Anklam",
            "Annaberg-Buchholz",
            "Ansbach",
            "Apolda",
            "Arnsberg",
            "Arnstadt",
            "Artern",
            "Aschaffenburg",
            "Aschendorf",
            "Aschersleben",
            "Aue",
            "Auerbach/Vogtland",
            "Augsburg",
            "Aurich",
            "Backnang",
            "Bad Aibling",
            "Bad Belzig",
            "Bad Bergzabern",
            "Bad Berleburg",
            "Bad Brückenau",
            "Bad Doberan",
            "Bad Dürkheim",
            "Bad Ems",
            "Bad Fallingbostel",
            "Bad Freienwalde",
            "Bad Gandersheim",
            "Bad Hersfeld",
            "Bad Homburg vor der Höhe",
            "Bad Kissingen",
            "Bad Kreuznach",
            "Bad Langensalza",
            "Bad Liebenwerda",
            "Bad Mergentheim",
            "Bad Neuenahr-Ahrweiler",
            "Bad Neustadt an der Saale",
            "Bad Oldesloe",
            "Bad Reichenhall",
            "Bad Salzungen",
            "Bad Schwalbach",
            "Bad Segeberg",
            "Bad Tölz",
            "Baden-Baden",
            "Balingen",
            "Bamberg",
            "Bautzen",
            "Bayreuth",
            "Beckum",
            "Beeskow",
            "Beilngries",
            "Belzig",
            "Berchtesgaden",
            "Bergen auf Rügen",
            "Bergen/Rügen",
            "Bergheim",
            "Bergisch Gladbach",
            "Bergzabern",
            "Berleburg",
            "Berlin",
            "Bernau",
            "Bernburg",
            "Bernkastel-Kues",
            "Bersenbrück",
            "Biberach an der Riß",
            "Biedenkopf",
            "Bielefeld",
            "Bingen",
            "Birkenfeld",
            "Bischofswerda",
            "Bitburg",
            "Bitterfeld",
            "Böblingen",
            "Bochum",
            "Bogen",
            "Bonn",
            "Borken",
            "Borna",
            "Bottrop",
            "Brake",
            "Brake in Lippe",
            "Brand-Erbisdorf",
            "Brandenburg",
            "Brandenburg an der Havel",
            "Braunlage",
            "Braunschweig",
            "Bremen",
            "Bremerhaven",
            "Bremervörde",
            "Brilon",
            "Bruchsal",
            "Brückenau",
            "Buchen",
            "Büdingen",
            "Bühl",
            "Büren",
            "Burg",
            "Burgdorf",
            "Burglengenfeld",
            "Burgsteinfurt",
            "Bützow",
            "Calau",
            "Calw",
            "Celle",
            "Cham",
            "Chemnitz",
            "Clausthal-Zellerfeld",
            "Cloppenburg",
            "Coburg",
            "Cochem",
            "Coesfeld",
            "Cottbus",
            "Crailsheim",
            "Cuxhaven",
            "Dachau",
            "Dannenberg",
            "Darmstadt",
            "Daun",
            "Deggendorf",
            "Delitzsch",
            "Delmenhorst",
            "Demmin",
            "Dessau-Roßlau",
            "Detmold",
            "Dieburg",
            "Diepholz",
            "Dietzenbach",
            "Diez",
            "Dillenburg",
            "Dillingen an der Donau",
            "Dingolfing",
            "Dinkelsbühl",
            "Dinslaken",
            "Dippoldiswalde",
            "Döbeln",
            "Donaueschingen",
            "Donauwörth",
            "Dortmund",
            "Dresden",
            "Duderstadt",
            "Duisburg",
            "Düren",
            "Düsseldorf",
            "Ebermannstadt",
            "Ebern",
            "Ebersberg",
            "Eberswalde",
            "Eberswalde-Finow",
            "Eckernförde",
            "Eggenfelden",
            "Ehingen",
            "Eichstätt",
            "Eilenburg",
            "Einbeck",
            "Eisenach",
            "Eisenberg",
            "Eisenhüttenstadt",
            "Eisleben",
            "Elmshorn1",
            "Emden",
            "Emmendingen",
            "Erbach",
            "Erding",
            "Erfurt",
            "Erkelenz",
            "Erlangen",
            "Eschenbach in der Oberpfalz",
            "Eschwege",
            "Essen",
            "Esslingen am Neckar",
            "Euskirchen",
            "Eutin",
            "Fallingbostel",
            "Feuchtwangen",
            "Finsterwalde",
            "Flensburg",
            "Flöha",
            "Forchheim",
            "Forst",
            "Frankenberg",
            "Frankenthal",
            "Frankfurt",
            "Frankfurt am Main",
            "Freiberg",
            "Freiburg",
            "Freiburg im Breisgau",
            "Freising",
            "Freital",
            "Freudenstadt",
            "Freyung",
            "Friedberg",
            "Friedrichshafen",
            "Fritzlar",
            "Fulda",
            "Fürstenfeldbruck",
            "Fürstenwalde",
            "Fürth",
            "Füssen",
            "Fußnote",
            "Gadebusch",
            "Gardelegen",
            "Garmisch-Partenkirchen",
            "Geilenkirchen",
            "Geithain",
            "Geldern",
            "Gelnhausen",
            "Gelsenkirchen",
            "Gemünden am Main",
            "Genthin",
            "Gera",
            "Germersheim",
            "Gerolzhofen",
            "Gießen",
            "Gifhorn",
            "Glauchau",
            "Göppingen",
            "Görlitz",
            "Goslar",
            "Gotha",
            "Göttingen",
            "Grafenau",
            "Gräfenhainichen",
            "Gransee",
            "Greifswald",
            "Greiz",
            "Grevenbroich",
            "Grevesmühlen",
            "Griesbach im Rottal",
            "Grimma",
            "Grimmen",
            "Groß-Gerau",
            "Großenhain",
            "Guben",
            "Gummersbach",
            "Günzburg",
            "Gunzenhausen",
            "Güstrow",
            "Gütersloh",
            "Hagen",
            "Hagenow",
            "Hainichen",
            "Halberstadt",
            "Haldensleben",
            "Halle",
            "Hamburg",
            "Hameln",
            "Hamm",
            "Hammelburg",
            "Hanau",
            "Hann. Münden",
            "Hannover",
            "Haßfurt",
            "Havelberg",
            "Hechingen",
            "Heide",
            "Heidelberg",
            "Heidenheim",
            "Heidenheim an der Brenz",
            "Heilbad Heiligenstadt",
            "Heilbronn",
            "Heinsberg",
            "Helmstedt",
            "Heppenheim",
            "Heppenheim an der Bergstraße",
            "Herford",
            "Herne",
            "Hersbruck",
            "Herzberg",
            "Hettstedt",
            "Hildburghausen",
            "Hildesheim",
            "Hilpoltstein",
            "Höchstadt an der Aisch",
            "Hof",
            "Hofgeismar",
            "Hofheim am Taunus",
            "Hofheim in Unterfranken",
            "Hohenmölsen",
            "Hohenstein-Ernstthal",
            "Holzminden",
            "Homberg",
            "Homburg",
            "Horb",
            "Höxter",
            "Hoyerswerda",
            "Hünfeld",
            "Hürth",
            "Husum",
            "Illertissen",
            "Ilmenau",
            "Ingelheim am Rhein",
            "Ingolstadt",
            "Iserlohn",
            "Itzehoe",
            "Jena",
            "Jessen",
            "Jever",
            "Jülich",
            "Jüterbog",
            "Kaiserslautern",
            "Kamenz",
            "Karlsruhe",
            "Karlstadt",
            "Kassel",
            "Kaufbeuren",
            "Kehl",
            "Kelheim",
            "Kemnath",
            "Kempen",
            "Kempten",
            "Kiel",
            "Kirchheimbolanden",
            "Kitzingen",
            "Kleve",
            "Klingenthal",
            "Klötze",
            "Koblenz",
            "Köln",
            "Königs Wusterhausen",
            "Königshofen im Grabfeld",
            "Konstanz",
            "Korbach",
            "Köthen",
            "Kötzting",
            "Krefeld",
            "Kreisstadt",
            "Kronach",
            "Krumbach",
            "Kulmbach",
            "Künzelsau",
            "Kusel",
            "Kyritz",
            "Lahn",
            "Lahr",
            "Landau an der Isar",
            "Landau in der Pfalz",
            "Landsberg am Lech",
            "Landshut",
            "Lauf an der Pegnitz",
            "Laufen",
            "Lauterbach",
            "Leer",
            "Leipzig",
            "Lemgo",
            "Leonberg",
            "Leverkusen",
            "Lichtenfels",
            "Limburg an der Lahn",
            "Lindau",
            "Lingen",
            "Lippstadt",
            "Löbau",
            "Lobenstein",
            "Lohr am Main",
            "Lörrach",
            "Lübbecke",
            "Lübben",
            "Lübeck",
            "Lübz",
            "Lüchow",
            "Luckau",
            "Luckenwalde",
            "Lüdenscheid",
            "Lüdinghausen",
            "Ludwigsburg",
            "Ludwigshafen am Rhein",
            "Ludwigslust",
            "Lüneburg",
            "Lutherstadt Eisleben",
            "Lutherstadt Wittenberg",
            "Magdeburg",
            "Mainburg",
            "Mainz",
            "Malchin",
            "Mallersdorf",
            "Mannheim",
            "Marburg",
            "Marburg an der Lahn",
            "Marienberg",
            "Marktheidenfeld",
            "Marktoberdorf",
            "Mayen",
            "Meiningen",
            "Meißen",
            "Meldorf",
            "Melle",
            "Mellrichstadt",
            "Melsungen",
            "Memmingen",
            "Meppen",
            "Merseburg",
            "Merzig",
            "Meschede",
            "Mettmann",
            "Miesbach",
            "Miltenberg",
            "Mindelheim",
            "Minden",
            "Mittelfranken",
            "Mittweida",
            "Moers",
            "Mönchengladbach",
            "Monschau",
            "Montabaur",
            "Mosbach",
            "Mühldorf am Inn",
            "Mühlhausen",
            "Mühlhausen/Thüringen",
            "Mülheim an der Ruhr",
            "Müllheim",
            "Münchberg",
            "München",
            "Münsingen",
            "Münster",
            "Nabburg",
            "Naila",
            "Nauen",
            "Naumburg",
            "Nebra",
            "Neu-Ulm",
            "Neubrandenburg",
            "Neuburg an der Donau",
            "Neuhaus am Rennweg",
            "Neumarkt in der Oberpfalz",
            "Neumünster",
            "Neunburg vorm Wald",
            "Neuruppin",
            "Neuss",
            "Neustadt am Rübenberge",
            "Neustadt an der Aisch",
            "Neustadt an der Haardt",
            "Neustadt an der Waldnaab",
            "Neustadt an der Weinstraße",
            "Neustadt im Schwarzwald",
            "Neustrelitz",
            "Neuwied",
            "Niebüll",
            "Niederbayern",
            "Nienburg",
            "Nienburg/Weser",
            "Niesky",
            "Norden",
            "Nordhausen",
            "Nordhorn",
            "Nördlingen",
            "Northeim",
            "Nürnberg",
            "Nürtingen",
            "Oberbayern",
            "Oberfranken",
            "Oberhausen",
            "Obernburg am Main",
            "Oberpfalz",
            "Oberviechtach",
            "Ochsenfurt",
            "Oelsnitz/Vogtland",
            "Offenbach am Main",
            "Offenburg",
            "Öhringen",
            "Oldenburg",
            "Oldenburg in Holstein",
            "Olpe",
            "Opladen",
            "Oranienburg",
            "Ort",
            "Oschatz",
            "Oschersleben",
            "Osnabrück",
            "Osterburg",
            "Osterholz-Scharmbeck",
            "Osterode am Harz",
            "Otterndorf",
            "Ottweiler",
            "Paderborn",
            "Papenburg",
            "Parchim",
            "Parsberg",
            "Pasewalk",
            "Passau",
            "Pegnitz",
            "Peine",
            "Perleberg",
            "Pfaffenhofen an der Ilm",
            "Pfarrkirchen",
            "Pforzheim",
            "Pinneberg",
            "Pinneberg1",
            "Pirmasens",
            "Pirna",
            "Plauen",
            "Plön",
            "Pößneck",
            "Potsdam",
            "Prenzlau",
            "Pritzwalk",
            "Prüm",
            "Quedlinburg",
            "Querfurt",
            "Rastatt",
            "Rathenow",
            "Ratzeburg",
            "Ravensburg",
            "Recklinghausen",
            "Regen",
            "Regensburg",
            "Rehau",
            "Reichenbach im Vogtland",
            "Remscheid",
            "Renchen",
            "Rendsburg",
            "Reutlingen",
            "Rheda-Wiedenbrück",
            "Ribnitz-Damgarten",
            "Riedenburg",
            "Riesa",
            "Rinteln",
            "Röbel/Müritz",
            "Rochlitz",
            "Rockenhausen",
            "Roding",
            "Rosenheim",
            "Roßlau",
            "Rostock",
            "Rotenburg",
            "Rotenburg an der Fulda",
            "Rotenburg in Hannover",
            "Roth",
            "Roth bei Nürnberg",
            "Rothenburg ob der Tauber",
            "Rottenburg an der Laaber",
            "Rottweil",
            "Rüdesheim am Rhein",
            "Rudolstadt",
            "Saalfeld",
            "Saarbrücken",
            "Saarburg",
            "Saarlouis",
            "Säckingen",
            "Salzgitter",
            "Salzwedel",
            "Sangerhausen",
            "Sankt Goar",
            "Sankt Goarshausen",
            "Sankt Ingbert",
            "Sankt Wendel",
            "Saulgau",
            "Scheinfeld",
            "Schleiden",
            "Schleiz",
            "Schleswig",
            "Schlüchtern",
            "Schmalkalden",
            "Schmölln",
            "Schönebeck",
            "Schongau",
            "Schrobenhausen",
            "Schwabach",
            "Schwaben",
            "Schwäbisch Gmünd",
            "Schwäbisch Hall",
            "Schwabmünchen",
            "Schwalmstadt",
            "Schwandorf",
            "Schwandorf in Bayern",
            "Schwarzenberg/Erzgebirge",
            "Schweinfurt",
            "Schwelm",
            "Schwerin",
            "Sebnitz",
            "Seelow",
            "Senftenberg",
            "Siegburg",
            "Siegen",
            "Sigmaringen",
            "Simmern",
            "Simmern/Hunsrück",
            "Sinsheim",
            "Soest",
            "Solingen",
            "Soltau",
            "Sömmerda",
            "Sondershausen",
            "Sonneberg",
            "Sonthofen",
            "Speyer",
            "Spremberg",
            "Springe",
            "St. Wendel",
            "Stade",
            "Stadthagen",
            "Stadtroda",
            "Stadtsteinach",
            "Staffelstein",
            "Starnberg",
            "Staßfurt",
            "Steinfurt",
            "Stendal",
            "Sternberg",
            "Stockach",
            "Stollberg/Erzgebirge",
            "Stralsund",
            "Strasburg",
            "Straubing",
            "Strausberg",
            "Stuttgart",
            "Suhl",
            "Sulzbach-Rosenberg",
            "Syke",
            "Tauberbischofsheim",
            "Tecklenburg",
            "Templin",
            "Teterow",
            "Tettnang",
            "Tirschenreuth",
            "Titisee-Neustadt",
            "Tönning",
            "Torgau",
            "Traunstein",
            "Trier",
            "Tübingen",
            "Tuttlingen",
            "Überlingen",
            "Ueckermünde",
            "Uelzen",
            "Uffenheim",
            "Ulm",
            "Unna",
            "Unterfranken",
            "Usingen",
            "Vaihingen an der Enz",
            "Vechta",
            "Verden",
            "Viechtach",
            "Viersen",
            "Villingen",
            "Villingen-Schwenningen",
            "Vilsbiburg",
            "Vilshofen",
            "Vohenstrauß",
            "Waiblingen",
            "Waldmünchen",
            "Waldshut",
            "Waldshut-Tiengen",
            "Wangen im Allgäu",
            "Wanzleben",
            "Warburg",
            "Waren",
            "Warendorf",
            "Wasserburg am Inn",
            "Wegscheid",
            "Weiden in der Oberpfalz",
            "Weilburg",
            "Weilheim in Oberbayern",
            "Weimar",
            "Weißenburg in Bayern",
            "Weißenfels",
            "Weißwasser/Oberlausitz",
            "Werdau",
            "Wernigerode",
            "Wertingen",
            "Wesel",
            "Westerburg",
            "Westerstede",
            "Wetzlar",
            "Wiedenbrück",
            "Wiesbaden",
            "Wildeshausen",
            "Wilhelmshaven",
            "Winsen an der Luhe",
            "Wismar",
            "Wittenberg",
            "Wittlage",
            "Wittlich",
            "Wittmund",
            "Wittstock",
            "Witzenhausen",
            "Wolfach",
            "Wolfenbüttel",
            "Wolfhagen",
            "Wolfratshausen",
            "Wolfsburg",
            "Wolgast",
            "Wolmirstedt",
            "Worbis",
            "Worms",
            "Wunsiedel",
            "Wuppertal",
            "Würzburg",
            "Wurzen",
            "Zeitz",
            "Zell",
            "Zella-Mehlis",
            "Zerbst",
            "Zeulenroda",
            "Ziegenhain",
            "Zirndorf",
            "Zittau",
            "Zossen",
            "Zschopau",
            "Zweibrücken",
            "Zwickau"});
            this.CityCbx.Location = new System.Drawing.Point(156, 46);
            this.CityCbx.Name = "CityCbx";
            this.CityCbx.Size = new System.Drawing.Size(345, 27);
            this.CityCbx.TabIndex = 1;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(71, 97);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(76, 19);
            this.label2.TabIndex = 0;
            this.label2.Text = "Keyword:";
            // 
            // KeywordTbx
            // 
            this.KeywordTbx.Location = new System.Drawing.Point(156, 95);
            this.KeywordTbx.Name = "KeywordTbx";
            this.KeywordTbx.Size = new System.Drawing.Size(167, 27);
            this.KeywordTbx.TabIndex = 2;
            // 
            // bsSett
            // 
            this.bsSett.DataSource = typeof(Databox.Libs.Jobboerse.ExtSettings);
            // 
            // ucExtSettings
            // 
            this.Appearance.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.Appearance.Options.UseFont = true;
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 19F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.KeywordTbx);
            this.Controls.Add(this.CityCbx);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "ucExtSettings";
            this.Size = new System.Drawing.Size(702, 329);
            this.Load += new System.EventHandler(this.ucExtSettings_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bsSett)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.BindingSource bsSett;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        public System.Windows.Forms.ComboBox CityCbx;
        public System.Windows.Forms.TextBox KeywordTbx;
    }
}
